NSS Lucianita dice hola a los Kidans
Helixis/CEV-Eris pull request #12
Opened 2020-06-07 16:19 UTC by Evankhell561

## About The Pull Request
Portea a los Kidans de paradise, más o menos.

## Why It's Good For The Game
Cuando nos mudamos de code dijimos que podriamos traer a algunas de las razas viejas al nuevo code

## Changelog
:cl:
add: Kidans
/:cl:

2020-06-07 18:50 UTC, Silverexperience requested changes
Los sprites y otras carpetas de codigo lo podrias meter en las carpetas hispania.

2020-06-07 22:46 UTC, Silverexperience requested changes

2020-06-07 22:46 UTC, Silverexperience commented on code/__HELPERS/global_lists.dm
> +
Este espacio sobra.

2020-06-07 22:46 UTC, Silverexperience commented on code/datums/datacore.dm
> +
¿Y este espacio?

2020-06-07 22:46 UTC, Silverexperience commented on code/modules/organs/external/_external.dm
> +
Sobraria un espacio

2020-06-07 22:46 UTC, Silverexperience commented on code/__DEFINES/species_languages.dm
> +
Este espacio sobraria.

2020-06-07 22:46 UTC, Silverexperience commented on code/__DEFINES/is_helpers.dm
> +
Se podria quitar este espacio.

2020-06-07 23:23 UTC, Silverexperience requested changes
Los kidans supuestamente no pueden llevar gafas.

2020-06-07 23:27 UTC, Silverexperience commented
¿Hiciste que los Kidans tengan perks o stats especiales?

2020-06-08 01:35 UTC, Evankhell561 commented
> Los sprites y otras carpetas de codigo lo podrias meter en las carpetas hispania.

listo

2020-06-08 01:36 UTC, Evankhell561 commented
> ¿Hiciste que los Kidans tengan perks o stats especiales?

en la descripcion estan

2020-06-08 01:42 UTC, Evankhell561 commented
Puedes testear esto cuado quieras, el travis esta fallando por el DC pero el code compila bien. en un rato lo reparo.

2020-06-08 02:06 UTC, Evankhell561 commented
El problema viene de que cambie la carpeta Hispania a hispania. La idea de poner los nombres en minusculas es para facilitar el trabajo de los que usan la consola, así que poner la primera letra en mayusculas y lo demás en minusculas es peor que dejarlo todo en mayusculas.

2020-06-08 11:24 UTC, Silverexperience requested changes
- Podrías hacer que tampoco puedan llevar gafas.

- Cuando no hay gravedad y ellos se pueden mover sigue escuchándose como si caminaran.

- Las funciones de Heterocromía y los de solo poseer un ojo causan efectos muy extraños
![imagen](https://user-images.githubusercontent.com/58746682/84021174-65633880-a984-11ea-8b9b-a4751441cb1f.png)
Como aquí, que el solo tener el ojo derecho se traduce en añadirle un punto naranja.
La Heterocromía simplemente no funciona.

- Los accesorios de ropa interior no le funcionan.

- ¿Lo de que no puedan añadirse más idiomas es apropósito? 

- Los emotes no parecen funcionar.

- No parece que se puedan invocar kidans en el menú de game panel.

- La bioluminiscencia que tenían se podría añadir aquí también.

- ¿Las gamas de colores desde rojo a negro son  apropósito? Se ven algo raras.
![imagen](https://user-images.githubusercontent.com/58746682/84021272-92175000-a984-11ea-8779-d9dce386c7c5.png)
![imagen](https://user-images.githubusercontent.com/58746682/84021285-9cd1e500-a984-11ea-866a-100419b8343e.png)
![imagen](https://user-images.githubusercontent.com/58746682/84021302-a52a2000-a984-11ea-9dc9-a7a12e87e5df.png)
![imagen](https://user-images.githubusercontent.com/58746682/84021666-55982400-a985-11ea-85d0-a852d343a29e.png)
Y sus antenas y cuernos no cambian de color aunque eso no importa mucho.

- A nivel de lore ¿Porque no podrían trabajar en el NT cristiano? Creo que en ningún momento ponía nada de que fueran racistas a las demás especies, además el implante se los sigues pudiendo poner.

2020-06-08 11:28 UTC, Evankhell561 commented
> La bioluminiscencia que tenían se podría añadir aquí también.

Lo siento, esto no sucederá, no por mí. En cambio tendrán lo de la gravedad.

2020-06-08 11:28 UTC, Evankhell561 commented
> * A nivel de lore porque no podrían trabajar en el NT cristiano, creo que en ningún momento ponía nada de que fueran racistas a las demás especies, además el implante se los sigues pudiendo poner.

Welp, entonces quito eso.

2020-06-08 11:29 UTC, Silverexperience commented
> Lo siento, esto no sucederá, no por mí. En cambio tendrán lo de la gravedad.

Eso tampoco es necesario, solo era por si querías.

2020-06-08 11:30 UTC, Evankhell561 commented
> * Los accesorios de ropa interior no le funcionan.

Eso es a proposito. no me gusta que todas las razas alienigenas tengan que usar ropa interior. En especial si no es una raza de mamiferos.

2020-06-08 11:31 UTC, Evankhell561 commented
> > * A nivel de lore porque no podrían trabajar en el NT cristiano, creo que en ningún momento ponía nada de que fueran racistas a las demás especies, además el implante se los sigues pudiendo poner.
> 
> Welp, entonces quito eso.

No quisiera tener que intentar agregar más features.
sobre la ropa interior, si quieres se la pongo, es una variable.

2020-06-08 11:32 UTC, Silverexperience commented
> 
> 
> > * Los accesorios de ropa interior no le funcionan.
> 
> Eso es a proposito. no me gusta que todas las razas alienigenas tengan que usar ropa interior. En especial si no es una raza de mamiferos.

Solo era porque le salen seleccionables, si no pueden usarlos no se porque los puedes selecionar.

2020-06-08 11:35 UTC, Evankhell561 commented
> * ¿Lo de que no puedan añadirse más idiomas es apropósito?

No pero si ya que tienen un idioma propio y unico tampoco veo necesario cambiar todo el code para que puedan tener más por defecto. A este code le faltan muchas opciones de personalizacion de razas y el hecho de tener un idioma unico por defecto y que no afecte a tu cantidad de idiomas en general no estaba considerado por la gente de eris
(el code esta preparado para tener solo dos idiomas y el segundo hueco esta llenado por su idioma unico) Tampoco me pareciera bien que nadie tenga más de dos idiomas ni que puedan conocer idiomas humanos como el ruso.

2020-06-08 11:36 UTC, Evankhell561 commented
> > > * Los accesorios de ropa interior no le funcionan.
> > 
> > 
> > Eso es a proposito. no me gusta que todas las razas alienigenas tengan que usar ropa interior. En especial si no es una raza de mamiferos.
> 
> Solo era porque le salen seleccionables, si no pueden usarlos no se porque los puedes selecionar.

Because este code no esta preparado para muchas cosas, ya lo arreglo. Rip yo.

2020-06-08 11:38 UTC, Silverexperience commented
> 
> 
> > * ¿Lo de que no puedan añadirse más idiomas es apropósito?
> 
> No pero si ya que tienen un idioma propio y unico tampoco veo necesario cambiar todo el code para que puedan tener más por defecto. A este code le faltan muchas opciones de personalizacion de razas y el hecho de tener un idioma unico por defecto y que no afecte a tu cantidad de idiomas en general no estaba considerado por la gente de eris
> (el code esta preparado para tener solo dos idiomas y el segundo hueco esta llenado por su idioma unico) Tampoco me pareciera bien que nadie tenga más de dos idiomas ni que puedan conocer idiomas humanos como el ruso.

Dejadlo así entonces.

2020-06-08 11:51 UTC, Evankhell561 commented
> * Los emotes no parecen funcionar.
Listo.

2020-06-08 11:54 UTC, Evankhell561 commented
> Solo era porque le salen seleccionables, si no pueden usarlos no se porque los puedes selecionar.

listo

2020-06-08 11:57 UTC, Evankhell561 commented
> ¿Las gamas de colores desde rojo a negro son apropósito? Se ven algo raras.
Les dejé la opcion de elegir el tono de piel como los humanos. creo que en paradise no la tenian, si quieres se las quito pero si pones un suelo distinto no se ve tan mal (en especial si no ponen el tono más oscuro). Tambien le daré posibilidad de pintarse las antenas y los cuernos del color que quieran.

2020-06-08 12:07 UTC, Silverexperience commented
> 
> 
> > ¿Las gamas de colores desde rojo a negro son apropósito? Se ven algo raras.
> 
> Les dejé la opcion de elegir el tono de piel como los humanos. creo que en paradise no la tenian, si quieres se las quito pero si pones un suelo distinto no se ve tan mal (en especial si no ponen el tono más oscuro). Tambien le daré posibilidad de pintarse las antenas y los cuernos del color que quieran.

Puedes dejarle los colores pero el negro puro es raro.

2020-06-08 12:28 UTC, Silverexperience commented
Luego, quizás algún trabajo se le podría bloquear por lore aunque ninguno se me ocurre más alla de los ingenieros y los Excelsior.

2020-06-08 12:40 UTC, Evankhell561 commented
> * Podrías hacer que tampoco puedan llevar gafas.

Listo

2020-06-08 12:41 UTC, Evankhell561 commented
> > > ¿Las gamas de colores desde rojo a negro son apropósito? Se ven algo raras.
> > 
> > 
> > Les dejé la opcion de elegir el tono de piel como los humanos. creo que en paradise no la tenian, si quieres se las quito pero si pones un suelo distinto no se ve tan mal (en especial si no ponen el tono más oscuro). Tambien le daré posibilidad de pintarse las antenas y los cuernos del color que quieran.
> 
> Puedes dejarle los colores pero el negro puro es extraño.
> No solo porque no se vea en la selección sino también dentro del juego.

podria intentar bajarle mucho el maximo tono que puedan elegir.

2020-06-08 12:43 UTC, Evankhell561 commented
> Luego, quizás algún trabajo se le podría bloquear por lore aunque ninguno se me ocurre más alla de los ingenieros y los Excelsior.

de momento hice que pudieran trabajar en la iglesia, pero deje el code que bloquea jobs.

2020-06-08 12:51 UTC, Evankhell561 commented
> Las funciones de Heterocromía y los de solo poseer un ojo causan efectos muy extraños

creo que les deshabilitaré esto.

2020-06-08 13:24 UTC, Evankhell561 commented
> Las funciones de Heterocromía y los de solo poseer un ojo causan efectos muy extraños

creo que les deshabilitaré esto.

> * Las funciones de Heterocromía y los de solo poseer un ojo causan efectos muy extraños
>   ![imagen](https://user-images.githubusercontent.com/58746682/84021174-65633880-a984-11ea-8b9b-a4751441cb1f.png)

Creo que logré resolver, esto. ya testeo.

2020-06-08 19:45 UTC, Evankhell561 commented
> Cuando no hay gravedad y ellos se pueden mover sigue escuchándose como si caminaran.

Uhm, esto es lo unico que me ha faltado por revisar. Esto funciona asi hasta cuado tienes el jetpack puesto. No cambiaré esto.

2020-06-08 23:03 UTC, Silverexperience requested changes
- Por lo que veo los cuernos han desaparecido y sobre las antenas ¿No se podría hacer que no puedas tener antenas de colores muy raros? Aunque no le quede mal el rosa u otros colores no es muy del estilo. Si no se puede dejalo asi.
![imagen](https://user-images.githubusercontent.com/58746682/84087845-52d01a00-a9eb-11ea-819c-75ec2954d99e.png)

- ¿Esto podria tener algun problema con las especies que querian añadir en Eris?

- Lo que dices de "ahora no pueden llevar gafas", pues...
![imagen](https://user-images.githubusercontent.com/58746682/84088065-ef92b780-a9eb-11ea-8284-e5edb32dfcef.png)

2020-06-09 15:56 UTC, Silverexperience approved these changes
Bien, todo en orden.

2020-06-24 18:12 UTC, Silverexperience requested changes
Deberias añadir un sistema para poder bloquear las especies o bloquearlo directamente en este PR para el evento de Helix.

Tiene conflictos.

2020-06-25 22:12 UTC, Evankhell561 commented
> Deberias añadir un sistema para poder bloquear las especies o bloquearlo directamente en este PR para el evento de Helix.
> 
> Tiene conflictos.

no idea de como hacer eso pero podria loquearlos en este pr.

2020-06-25 22:15 UTC, Evankhell561 commented
> No idea de como hacer eso pero podria bloquearlos en este pr.

Bloqueado, espero.

2020-06-28 22:53 UTC, merged