Bajada de precio a Penetrator
Helixis/CEV-Eris pull request #18
Opened 2020-08-12 19:23 UTC by Sombrahide

## About The Pull Request
Se ha sobrescrito la variable por defecto del objeto mag_accel para bajar su precio a la hora de exportarlo, evitando de esta manera que cargo se haga rico abusando de su exportacion.

## Why It's Good For The Game
Previene que la gente de cargo pueda abusar de la venta de Penetrators o por lo menos alivia el problema al hacerlo menos productivo.

## Changelog
:cl:
balance: Se bajo el precio de exportacion del Pentrator de 500 a 400 creditos.
/:cl:

2020-08-12 19:26 UTC, Evankhell561 approved these changes

2020-08-12 19:49 UTC, SagaStars commented
Increible PR, mis ancestros nunca olvidaran este momento historico.

2020-08-12 22:51 UTC, Silverexperience requested changes
En tu changelog pones que el precio cambia de 500 a 400 pero realmente cambia a 300 creditos.
¿Cual es el precio que le quieres poner?

2020-08-12 23:00 UTC, Silverexperience reviewed
Aunque bajes el precio si la productividad es alta seguirá siendo una forma muy fácil de enriquecerse.
¿Estás seguro de que la bajada de precio funcionaría?

2020-08-12 23:03 UTC, Silverexperience reviewed
Para poder ahorrar conflictos al ser un cambio tan pequeño que quizás a los rusos también les interese podrías hacerlo en su repositorio y ya pasaría al nuestro, no veo la necesidad de que este aquí.

2020-08-12 23:05 UTC, Sombrahide commented
De acuerdo, en ese caso mirare de pasarlo por el suyo, esto sobretodo ha sido una pequeña practica para ver como codear para el server.

2020-08-12 23:06 UTC, Sombrahide commented
Cierto, perdona que no lo pusiera en el anterior comentario, mas como crees tu que se podria prevenir que se vuelva algo tan beneficioso? Encuentro que siempre debera generar algo de beneficio en comparacion a los recursos gastados, mas no soy un experto en ciencias o cargo para saber cual seria un buen precio para el mismo.

2020-08-12 23:10 UTC, Silverexperience commented
> 
> 
> Cierto, perdona que no lo pusiera en el anterior comentario, mas como crees tu que se podria prevenir que se vuelva algo tan beneficioso? Encuentro que siempre debera generar algo de beneficio en comparacion a los recursos gastados, mas no soy un experto en ciencias o cargo para saber cual seria un buen precio para el mismo.

Como por lo que veo la mejora es totalmente gratuita de construir podrias hacer que cueste materiales o que no valiese nada.

2020-08-12 23:18 UTC, Silverexperience commented
Para hacer el PR en su repositorio seria como en este pero cuando en la seleccion eliges compararlo con el repositorio de discordia y no el de Helix.
![imagen](https://user-images.githubusercontent.com/58746682/90077571-cf8cb680-dd02-11ea-90de-e6f0ae537eb9.png)

2020-08-12 23:26 UTC, Sombrahide commented
Entendido, muchas gracias Silver, en cuanto termine de colocar los peinados de Ume me pondre a enviar la solicitud a su git

2020-08-13 13:08 UTC, Sombrahide commented
Understood, I did not realize that someone else had made the change

2020-08-13 13:08 UTC, closed without merging