Añadidos los peinados de Ume
Helixis/CEV-Eris pull request #19
Opened 2020-08-12 23:29 UTC by Sombrahide

## About The Pull Request
Añadido al codigo todos los peinados de Ume que se encuentran actualmente en el git de hipania paradise.

## Why It's Good For The Game
Tenemos mas peinados disponibles para nuestros personajes

## Changelog
:cl:
add: Añadido 22 peinados creados por Ume
imageadd: Añadido 22 nuevos iconos creados por Ume
/:cl:

2020-08-12 23:44 UTC, Sombrahide commented
Sorry, i have pulled all the changes of our code

2020-08-12 23:52 UTC, Silverexperience requested changes
- En el PR de los pelos de ume para que los archivos los pueda leer el programa necesita tener el check activado cuando se compile.

![imagen](https://user-images.githubusercontent.com/58746682/90079162-6e1b1680-dd07-11ea-8b15-19d756c6f70c.png)

- Los pelos de ume seria mejor que los metieras en un archivo dentro de la carpeta icons/hispania y lo reedireccionaras ahi.

2020-08-12 23:52 UTC, Silverexperience commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +	icon_state = "low_twins_s"
Al final del código hay que dejar un espacio en blanco.

2020-08-12 23:53 UTC, Sombrahide commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +	icon_state = "low_twins_s"
Entendido, ahora me pondre a ello

2020-08-13 11:38 UTC, Sombrahide commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +	icon_state = "low_twins_s"
Espacio en blanco añadido, ademas de haber puesto los pelos de ume en un archivo en la direccion que me recomendastes.

2020-08-13 19:42 UTC, Evankhell561 requested changes

2020-08-13 19:42 UTC, Evankhell561 commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +/datum/sprite_accessory/hair
no existe esto ya en el codigo?
tengo dudas sobre esta linea. Si esta es la ruta de los cabellos del repo principal y cambias al tura entonces los peinados de la rama principal no se visualizarán.

2020-08-13 19:44 UTC, Evankhell561 requested changes
También, por qué has modificado dos archivos .dmi?

2020-08-13 19:46 UTC, Silverexperience commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +/datum/sprite_accessory/hair
Ambros fijate en el código de los pelos de los kidans

2020-08-13 20:42 UTC, Sombrahide commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +/datum/sprite_accessory/hair
Se que en lo de los kidan tienen una ruta diferente, mas tenerla igual que la del codigo principal no la afecta, los peinados de la rama principal se siguen visualizando, es algo que comprobe antes de hacer el pr mientras comprovaba que los peinados de ume se viesen.

2020-08-13 20:43 UTC, Sombrahide commented
> 
> 
> También, por qué has modificado dos archivos .dmi?

Se debe a que antes los peinados de ume estaban en la rama principal, pero Silver de dijo que los cambiase a una aparte, cosa que he echo y por supuesto tuve que quitarlos de la principal.

2020-08-13 20:56 UTC, Evankhell561 requested changes

2020-08-13 20:56 UTC, Evankhell561 commented on code/hispania/modules/sprite_accessories/human/human_hair.dm
> +/datum/sprite_accessory/hair
No, no está bien. Lo que pasa es que metiste los cabellos de ume en el dmi de la rama princial y aun no los has borrado.

2020-08-13 21:55 UTC, Evankhell561 approved these changes

2020-08-13 22:42 UTC, Silverexperience approved these changes

2020-08-13 22:45 UTC, merged