WIP Borg Weapons
Helixis/CEV-Eris pull request #32
Opened 2020-09-22 22:19 UTC by NervalARS

## About The Pull Request

El arma taser de los Cyborgs de seguridad a sido remplazada por un arma hibrida que permite tanto disparar un taser como un rayo laser.

## Why It's Good For The Game

Esto dara mas versatilidad a los robots de sec en situación de combate, se acabara el ser forzado a usar el cuerpo a cuerpo para eliminar a un enemigo.

## Changelog
:cl:
add: Added new things
balance: rebalanced something
del: old things
/:cl:

2020-09-23 17:02 UTC, Silverexperience requested changes

2020-09-23 17:02 UTC, Silverexperience commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +		)
Pon un espacio al final del código.

2020-09-23 17:02 UTC, Silverexperience commented on code/modules/projectiles/guns/energy/egun.dm
> +
Quita los dos espacios al final de este archivo

2020-09-24 11:38 UTC, Silverexperience requested changes
- Cuando disparas el arma tu puntero cambia y solo se puede quitar cambiando de modo o aveces ni se quita.

- Decias que con alt + click se puede cambiar el seguro, pero no parece funcionar.

2020-09-24 11:38 UTC, Silverexperience commented on code/modules/projectiles/guns/energy/egun.dm
> +		update_mode()
Te dejaste un espacio al final del código.

2020-09-24 11:38 UTC, Silverexperience commented on code/modules/mob/living/silicon/robot/robot_upgrades.dm
> +	var/obj/item/weapon/gun/energy/gun/mounted/cyborg/T = locate() in R.module
¿Por qué cambias la mejora del taser al del arma hibrida?
Y si lo quieres cambiar cambia también el texto que no tiene sentido que al poner la mejora te digan que has añadido un taser pero en realidad es un arma hibrida.

2020-09-24 11:38 UTC, Silverexperience commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +/obj/item/weapon/gun/energy/gun/mounted/cyborg
La mayoría de las cosas de este objeto son heredadas; podrías quitarlas.

2020-09-24 11:45 UTC, NervalARS commented
El seguro fue retirado, una vez que se cambió el arma a la versión montada.
En respecto al puntero lo corregiré.

El jue., 24 sept. 2020 13:39, Silverexperience <notifications@github.com>
escribió:

> *@Silverexperience* requested changes on this pull request.
>
>    -
>
>    Cuando disparas el arma tu puntero cambia y solo se puede quitar
>    cambiando de modo o aveces ni se quita.
>    -
>
>    Decias que con alt + click se puede cambiar el seguro, pero no parece
>    funcionar.
>
> ------------------------------
>
> In code/modules/projectiles/guns/energy/egun.dm
> <https://github.com/Helixis/CEV-Eris/pull/32#discussion_r494233077>:
>
> > \ No newline at end of file
>
> +		update_mode()
>
>
> Te dejaste un espacio al final del código.
> ------------------------------
>
> In code/modules/mob/living/silicon/robot/robot_upgrades.dm
> <https://github.com/Helixis/CEV-Eris/pull/32#discussion_r494235775>:
>
> > @@ -128,7 +128,7 @@
>
>  		to_chat(usr, "There's no mounting point for the module!")
>
>  		return 0
>
>
>
> -	var/obj/item/weapon/gun/energy/taser/mounted/cyborg/T = locate() in R.module
>
> +	var/obj/item/weapon/gun/energy/gun/mounted/cyborg/T = locate() in R.module
>
>
> ¿Por qué cambias la mejora del taser al del arma hibrida?
> Y si lo quieres cambiar cambia también el texto que no tiene sentido que
> al poner la mejora te digan que has añadido un taser pero en realidad es un
> arma hibrida.
> ------------------------------
>
> In code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> <https://github.com/Helixis/CEV-Eris/pull/32#discussion_r494243309>:
>
> > @@ -0,0 +1,20 @@
>
> +/obj/item/weapon/gun/energy/gun/mounted/cyborg
>
>
> La mayoría de las cosas de este objeto son heredadas; podrías quitarlas.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Helixis/CEV-Eris/pull/32#pullrequestreview-495464817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMQR5FEA3UJGQKB2JVXTSDSHMVV3ANCNFSM4RWJY7ZA>
> .
>

2020-09-24 14:05 UTC, Evankhell561 requested changes

2020-09-24 14:05 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +/obj/item/weapon/gun/energy/egun
Está ruta no existía ya? Parece que la estás duplicado.

2020-09-24 14:09 UTC, Evankhell561 requested changes
El pr estaba casi listo, silver sólo te pidió unas pequeñas cosas pero parece que te has vuelto un lío. Recomendaría dar uno o dos pasos atrás.

2020-09-25 20:27 UTC, Silverexperience requested changes
- El puntero sigue teniendo el problema de no poder quitarse.

- Ahora la pistola ya no recoge la energia del borg.

- Sigue estando la linea del final en  code/modules/projectiles/guns/energy/egun.dm.

2020-09-25 22:15 UTC, Silverexperience requested changes
- El puntero sigue igual.

- Cuando decia que tenia cosas heredadas no me referia a que quites las herencias y las pegues ahi, puede quedar asi pero es un poco lioso e inecesario.

2020-09-26 07:35 UTC, Evankhell561 requested changes

2020-09-26 07:35 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +	can_dual = 1
= TRUE

2020-09-26 07:35 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +	)
Por una línea nueva acá.

2020-09-26 09:31 UTC, NervalARS commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +	can_dual = 1
No entiendo lo que intentas decir. El item_state deberia estar en TRUE?

2020-09-26 18:05 UTC, Silverexperience requested changes

2020-09-26 18:05 UTC, Silverexperience commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +	charge_meter = FALSE
¿Porque lo pones falso? Poder ver las balas que quedan en el sprite no es algo malo.

2020-09-26 18:05 UTC, Silverexperience commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	src.emag = new /obj/item/weapon/gun/energy/plasma/mounted/blitz(src)
¿Porque este cambio de armas en el emag?

2020-09-26 18:05 UTC, Silverexperience commented on code/hispania/game/objects/items/weapons/guns/energy/egun.dm
> +	recharge_time = 10
Podrias reducir el tiempo de carga. Tarda bastante y al usar energia del borg tampoco tendras infinitos disparos.

2020-09-26 18:54 UTC, NervalARS commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	src.emag = new /obj/item/weapon/gun/energy/plasma/mounted/blitz(src)
Para que el borg no tenga dos armas laser

2020-09-27 22:57 UTC, merged