Añade el Defibrillator al Juego (Work in Progress)
Helixis/CEV-Eris pull request #35
Opened 2020-09-29 17:24 UTC by Danaleja2005

## About The Pull Request

WIP 

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2020-10-04 23:13 UTC, Evankhell561 commented
Tu wip es sólo una línea en blanco?

2020-10-05 17:16 UTC, Danaleja2005 commented
> Tu wip es sólo una línea en blanco?

Eh?

2020-10-09 09:14 UTC, Evankhell561 requested changes

2020-10-09 09:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/obj/item/weapon/cell/cell
Tienes que definir el tipo de la batería o se le podrá poner cualquiera. Te recomiendo una medium.

2020-10-09 09:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		new_overlays += "[initial(icon_state)]-charge[ratio]"
No es necesario poner initial( sin Bargo no quites el argumento de ese proc.

2020-10-09 09:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		new_overlays += "[initial(icon_state)]-nocell"
Lo mismo acá

2020-10-09 09:14 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human.dm
> +/// Resuscitate for Defib by Danaleja2005
Esto para hispania.

2020-10-09 09:14 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human.dm
> +//Checks that the species has a "head" (brain containing organ) and that hit_	zone refers to it.
No cambies está línea.

2020-10-09 09:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		busy = 0
FALSE

2020-10-09 09:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = 0
FALSE

2020-10-09 11:53 UTC, Danaleja2005 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		new_overlays += "[initial(icon_state)]-nocell"
seguro de eso?, creo que en alguna prueba que realice se jodian los sprites, aunque no estoy seguro si fue por un codigo que andaba testeando o por eso, lo testeare y te digo

2020-10-10 01:07 UTC, Evankhell561 requested changes

2020-10-10 01:07 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/defibrillator/attack_self(var/mob/living/user)
no pongas var/ en los argumentos de un proc.

2020-10-10 01:07 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/defibrillator/proc/check_charge(var/charge_amt)
no pongas "var/" en los argumentos de un proc.

2020-10-10 01:07 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/defibrillator/attack(mob/living/M, mob/living/user, var/target_zone)
var/

2020-10-10 01:07 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/defibrillator/apply_hit_effect(mob/living/target, mob/living/user, var/hit_zone)
var/

2020-10-10 01:14 UTC, Evankhell561 requested changes

2020-10-10 01:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +			to_chat(user, "<span class='notice'>You remove the cell from the [src].</span>")
en eris no usamos "<span class='notice'>bla bla.</span>" sino SPAN_NOTICE("bla bla.")

2020-10-10 01:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	cooldown = 1
cooldown = TRUE

2020-10-10 01:14 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +obj/item/weapon/defibrillator/proc/set_cooldown(var/delay)
te falto el / adelante de la ruta

2020-10-10 14:54 UTC, Evankhell561 requested changes

2020-10-10 14:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/suitable_cell = /obj/item/weapon/cell/medium
en tu ultimo commit cambiaste esto, yo no pedi eso. no está mal pero tampoco es lo que habia pedido.

2020-10-10 14:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/obj/item/weapon/cell/cell
te pedi cambiar fue esto a una cell tipo medium
var/obj/item/weapon/cell/medium/cell

2020-10-10 14:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/chargetime = (2 SECONDS)
estos parentesis no son necesarios.

2020-10-10 14:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/cooldowntime = (5 SECONDS)
estos parentesis no son necesarios.

2020-10-17 06:54 UTC, Evankhell561 requested changes

2020-10-17 06:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/obj/item/weapon/cell/cell
no has resuelto esto.

2020-10-17 06:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/cooldowntime = (5 SECONDS)
no has resuelto esto

2020-10-17 06:54 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/chargetime = (2 SECONDS)
ni esto

2020-10-17 07:00 UTC, Evankhell561 requested changes

2020-10-17 07:00 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/defibrillator/Initialize()
iniciar con una bateria debe ser algo unico de un desfibrilador hijo, el desfibrilador padre no deberia iniciar con bateria.

2020-10-17 07:00 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		to_chat(user, SPAN_WARNING("The [H]'s Hearth is active!."))
en realidad lo que estás chequeando es si el objetivo está muerto asi que deberia decir "el paciente está vivo!"

2020-10-17 07:00 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human.dm
> +	reset_view(A)
esto es un dm de eris, no debes cambiarlo solo para esto

2020-10-22 04:24 UTC, Evankhell561 requested changes

2020-10-22 04:24 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		to_chat(user, SPAN_NOTICE("You turn the [src] [active ? "on" : "off"] ."))
`to_chat(user, SPAN_NOTICE("You turn the [src] [active ? "on" : "off"]."))`
el problema es que pusiste un espacio demas antes de poner el punto.

2020-10-22 04:24 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
no sé para que ne bay usaban esta variable pero en tu code no sirve para nada. quita toda referrencia a ello.

2020-10-22 04:43 UTC, Danaleja2005 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
cual?

2020-10-22 04:55 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
busy

2020-10-22 04:55 UTC, Evankhell561 requested changes
tu pr tiene conflictos.

2020-10-22 04:58 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
busy

2020-10-22 14:05 UTC, Danaleja2005 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
si se utiliza

2020-10-22 14:05 UTC, Danaleja2005 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	var/busy = FALSE
Basicamente es para que no andes defibrando a dos tios al mismo tiempo

2020-10-30 01:35 UTC, Silverexperience requested changes
Mete los sonidos en carpetas hispania

¿Los iconos no pueden estar en carpetas hispania?

Resuelve los conflictos.

2020-11-01 00:59 UTC, Evankhell561 requested changes

2020-11-01 00:59 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +	busy = FALSE
como hay dos do_after quita este de aca. y ponlo mas abajo, ya te digo donde.

2020-11-01 00:59 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +
`busy = TRUE` aca

2020-11-01 00:59 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +		return
`busy = FALSE`
aca

2020-11-01 00:59 UTC, Evankhell561 commented on code/hispania/game/objects/items/weapons/defibrillator.dm
> +
`busy = FALSE`
aca

2021-01-14 04:16 UTC, closed without merging